# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webshopdb
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: my-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
